apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mongo-deployment  # Name of the Deployment
  labels:
    app: mongo  # Labels for the Deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-db
  template:
    metadata:
      labels:
        app: mongo-db  # Labels for the Pods created by this Deployment
    spec:
      containers:
      - name: mongo-db
        image: mongo:6.0
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongodb-username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-secrets
              key: mongodb-password
        - name: MONGO_PORT
          valueFrom:
            configMapKeyRef:
              name: mongodb-config
              key: port
