apiVersion: v1
kind: Service
metadata:
  labels:
    app: budget-buddy-frontend
  name: budget-buddy-frontend-service
spec:
  selector:
    app: budget-buddy-frontend
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 80
