apiVersion: v1
kind: Service
metadata:
  name: backend-buddy-service
  labels:
    app: budget-buddy
spec:
  selector:
    app: budget-buddy
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  clusterIP: None
