apiVersion: apps/v1
kind: Deployment
metadata: 
  name: backend-buddy-backend-deployment
  labels:
    app: budget-buddy
    tier: backend  
spec:
  replicas: 3
  selector:
    matchLabels:
      app: budget-buddy
  template:
    metadata:
      labels:
        app: budget-buddy
    spec:
      containers:
      - name: backend-buddy
        image: jayasurya5454/budget-buddy-backend:latest
        ports:
          - containerPort: 5000   
        env:
        - name: MONGO_URI
        value: "mongodb://mongodb-service:27017/budget-buddy"