apiVersion: v1
kind: Service
metadata:
  name: backend-buddy-backend
  labels:
    app: budget-buddy
spec:
  ports:
    - port: 5000
      targetPort: 5000
  selector:
    app: budget-buddy
  clusterIP: None  